-- Run this in Supabase SQL Editor before/after deploying to Vercel.
-- It brings existing production databases up to date with the current app fields.

alter table public.immunizations add column if not exists is_minor_patient boolean;
alter table public.immunizations add column if not exists guardian_name text;
alter table public.immunizations add column if not exists guardian_email text;
alter table public.immunizations add column if not exists guardian_contact_number text;
alter table public.immunizations add column if not exists consent_given boolean;
alter table public.immunizations add column if not exists consent_given_by text;
alter table public.immunizations add column if not exists consent_statement text;
alter table public.immunizations add column if not exists created_by uuid references public.admin_users(id) on delete set null;

alter table public.animal_bites add column if not exists registration_no text;
alter table public.animal_bites add column if not exists date_registered date;
alter table public.animal_bites add column if not exists place_of_exposure text;
alter table public.animal_bites add column if not exists site_of_exposure text;
alter table public.animal_bites add column if not exists source_of_exposure text;
alter table public.animal_bites add column if not exists source_other_details text;
alter table public.animal_bites add column if not exists source_vaccination_status text;
alter table public.animal_bites add column if not exists status_of_animal_after_14_days text;
alter table public.animal_bites add column if not exists severity_category text;
alter table public.animal_bites add column if not exists wound_washing_done boolean;
alter table public.animal_bites add column if not exists rig_given boolean;
alter table public.animal_bites add column if not exists anti_rabies_vaccine_given boolean;
alter table public.animal_bites add column if not exists vaccine_generic_name text;
alter table public.animal_bites add column if not exists vaccine_brand_name text;
alter table public.animal_bites add column if not exists vaccine_route text;
alter table public.animal_bites add column if not exists post_exposure_schedule text;
alter table public.animal_bites add column if not exists schedule_d0 date;
alter table public.animal_bites add column if not exists schedule_d3 date;
alter table public.animal_bites add column if not exists schedule_d7 date;
alter table public.animal_bites add column if not exists schedule_d14 date;
alter table public.animal_bites add column if not exists schedule_d21 date;
alter table public.animal_bites add column if not exists schedule_d28 date;
alter table public.animal_bites add column if not exists is_minor_patient boolean;
alter table public.animal_bites add column if not exists guardian_name text;
alter table public.animal_bites add column if not exists guardian_email text;
alter table public.animal_bites add column if not exists guardian_contact_number text;
alter table public.animal_bites add column if not exists consent_given boolean;
alter table public.animal_bites add column if not exists consent_given_by text;
alter table public.animal_bites add column if not exists consent_statement text;
alter table public.animal_bites add column if not exists treatment_protocol text;
alter table public.animal_bites add column if not exists total_required_doses int not null default 4;
alter table public.animal_bites add column if not exists doses_administered int not null default 0;
alter table public.animal_bites add column if not exists days_between_doses int not null default 3;
alter table public.animal_bites add column if not exists last_dose_date date;
alter table public.animal_bites add column if not exists next_visit_date date;
alter table public.animal_bites add column if not exists treatment_status text not null default 'pending';
alter table public.animal_bites add column if not exists notes text;
alter table public.animal_bites add column if not exists created_by uuid references public.admin_users(id) on delete set null;
